services:
  - type: web
    name: ocr-multilang-service
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr tesseract-ocr-all && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
